name: ThinkStats2
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip:
    - cx-oracle
    - datetime
    - .
  - asn1crypto
  - astroid
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - lazy-object-proxy
  - libblas
  - libcblas
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libiconv
  - liblapack
  - liblapacke
  - libopenblas
  - libpng
  - libsodium
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - markupsafe
  - matplotlib
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - pylint
  - pyopenssl
  - pyqt
  - pyrsistent
  - pysocks
  - pytables
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - seaborn
  - send2trash
  - setuptools
  - scipy
  - scikit-learn
  - sip
  - six
  - soupsieve
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - wrapt
  - xlrd
  - xz
  - zeromq
  - zlib
